language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN="5faacafa-5b13-483e-a43a-288c06483f82"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - integer.args@gmail.com
    on_success: never # default: change
    on_failure: always # default: always